CREATE TABLE GroupeaseUser (
  id BIGSERIAL PRIMARY KEY,
  providerUserId TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  nickname TEXT NULL,
  pictureUrl TEXT NULL,
  lastUpdatedOn TIMESTAMP NOT NULL
);

CREATE TABLE Channel (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NULL,
  lastUpdatedOn TIMESTAMP NOT NULL
);

CREATE TABLE Member (
    id BIGSERIAL PRIMARY KEY,
    userId BIGSERIAL NOT NULL REFERENCES GroupeaseUser,
    ChannelId BIGSERIAL NOT NULL REFERENCES Channel,
    IsOwner BOOLEAN NOT NULL DEFAULT FALSE,
    -- Issue #31: Per channel profile fields to go here later
    skills TEXT NULL,
    availability TEXT NULL,
    goals TEXT NULL,
    LastUpdate TIMESTAMP NOT NULL
);

CREATE TABLE ChannelGroup (
    ID BIGSERIAL PRIMARY KEY,
    ChannelID BIGSERIAL NOT NULL REFERENCES Channel ON DELETE CASCADE,
    Name TEXT NOT NULL,
    Description TEXT,
    IsFull BOOLEAN NOT NULL DEFAULT FALSE,
    LastUpdate TIMESTAMP NOT NULL
);

CREATE TABLE GroupMember (
    GroupID BIGSERIAL NOT NULL REFERENCES ChannelGroup ON DELETE CASCADE,
    MemberID BIGSERIAL NOT NULL REFERENCES Member ON DELETE CASCADE,
    LastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GroupID, MemberID)
);

CREATE TABLE ChannelInvitation (
    ID BIGSERIAL PRIMARY KEY,
    ChannelID BIGSERIAL NOT NULL REFERENCES Channel ON DELETE CASCADE,
    SenderID BIGSERIAL NOT NULL REFERENCES GroupeaseUser ON DELETE CASCADE,
    recipientId BIGSERIAL NOT NULL REFERENCES GroupeaseUser ON DELETE CASCADE,
    Comments TEXT,
    LastUpdate TIMESTAMP NOT NULL
);

CREATE TABLE ChannelJoinRequest (
    ID BIGSERIAL PRIMARY KEY,
    ChannelID BIGSERIAL NOT NULL REFERENCES Channel ON DELETE CASCADE,
    userId BIGSERIAL NOT NULL REFERENCES GroupeaseUser ON DELETE CASCADE,
    Comments TEXT,
    LastUpdate TIMESTAMP NOT NULL
);

CREATE TABLE GroupInvitation (
    ID BIGSERIAL PRIMARY KEY,
    GroupID BIGSERIAL NOT NULL REFERENCES ChannelGroup ON DELETE CASCADE,
    SenderID BIGSERIAL NOT NULL REFERENCES Member ON DELETE CASCADE,
    RecipientID BIGSERIAL NOT NULL REFERENCES Member ON DELETE CASCADE,
    Comments TEXT,
    LastUpdate TIMESTAMP NOT NULL
);

CREATE TABLE GroupJoinRequest (
    ID BIGSERIAL PRIMARY KEY,
    GroupID BIGSERIAL NOT NULL REFERENCES ChannelGroup ON DELETE CASCADE,
    SenderID BIGSERIAL NOT NULL REFERENCES Member ON DELETE CASCADE,
    Comments TEXT,
    LastUpdate TIMESTAMP NOT NULL
);
